version: '3.8'
services:
    web:
      build: .
      ports:
        - "8080:8080"
    db:
      image: "postgresql"
      environment: 
        POSTGRES_PASSWORD: password
      volumes:
        - db-data: /var/lib/pgsql/data/
  
volume:
  db-data: