version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: guestbook-frontend
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - guestbook_network

networks:
  guestbook_network:
    driver: bridge
