version: '3.8'
services:
  app:
    build: ./backend
    container_name: guestbook-server
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_URL=${DB_URL}
    volumes: 
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db

  db:
    image: ${DB_IMAGE}
    container_name: guestbook-db
    restart: unless-stopped
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports: 
      - ${DB_PORT}
    volumes:
      - ${DB_VOLUME}

  frontend:
    build: ./frontend
    container_name: guestbook-frontend
    restart: unless-stopped
    volumes:
      - ./frontend:/app
    expose:
      - "8080"
    depends_on:
      - app
    

    nginx:
      build: ./nginx
      container_name: guestboox-nginx
      restart: unless-stopped
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/conf.d/:/etc/nginx/conf.d/
        - ./nginx/ssl/:/etc/nginx/ssl/
      depends_on:
        - frontend
        - app 

volumes:
  pgdata:
