version: '3.8'
services:
  backend:
    build: ./backend
    container_name: guestbook-server
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      - NODE_ENV=development
      - DB_URL=${DB_URL}
      - REDIS_URL=${REDIS_URL}
    volumes: 
      - ./backend:/app
      - /app/node_modules
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  db:
    image: postgres:15-alpine
    container_name: guestbook-db
    user: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports: 
      - "5685:5685"
    volumes:
      - dbdata:/var/lib/pgsql/data
      - ./database/postgresql.conf:/var/lib/pgsql/data/postgresql.conf
      - ./database/pg_hba.conf:/var/lib/pgsql/data/pg_hba.conf
      - ./database/ssl/pg-server.crt:/var/lib/pgsql/data/pg-server.crt
      - ./database/ssl/pg-server.key:/var/lib/pgsql/data/pg-server.key
    command: bash -c "chown postgres:postgres /var/lib/pgsql/data/pg-server.* && chmod 0600 /var/lib/pgsql/data/pg-server.* && postgres -c 'config_file=/var/lib/pgsql/data/postgresql.conf'"
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: guestbook-frontend
    restart: unless-stopped
    volumes:
      - ./frontend:/app
    expose:
      - "8080"
    depends_on:
      - backend
    command: npm run build
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    
  nginx:
    build: ./nginx
    container_name: guestbook-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/ssl/:/etc/nginx/ssl/
      - guestbook-nginx-logs:/app/nginx/logs/
    depends_on:
      - frontend
      - backend
      - redis
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  redis:
    image: redis:alpine
    container_name: guestbook-redis
    command: redis-server /usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/logs:/usr/local/etc/redis/logs
    ports:
      - "6969:6969"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
  dbdata:
  redis-data:
  guestbook-nginx-logs:
