version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: guestbook-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/ssl/:/etc/nginx/ssl/
      - ./nginx/logs/:/var/log/nginx/
    depends_on:
      - app
      - frontend
    networks:
      - guestbook_network

networks:
  guestbook_network:
    driver: bridge
